
# zhangwenqian @ BMP in ~/UNSW/capstone-project-3900w18aZEAL/backend on git:dev_frontend x [23:12:16] 
$ ls
Pipfile  a.txt    app.py   database setup.sh src      target

# zhangwenqian @ BMP in ~/UNSW/capstone-project-3900w18aZEAL/backend on git:dev_frontend x [23:12:17] 
$ ls
Pipfile  a.txt    app.py   database setup.sh src      target

# zhangwenqian @ BMP in ~/UNSW/capstone-project-3900w18aZEAL/backend on git:dev_frontend x [23:12:18] 
$ pwd           
/Users/zhangwenqian/UNSW/capstone-project-3900w18aZEAL/backend

# zhangwenqian @ BMP in ~/UNSW/capstone-project-3900w18aZEAL/backend on git:dev_frontend x [23:12:19] 
$ sh setup.sh
-e 
 项目后端部署开始 ... 

-e 
 安装pipenv（如果还没有安装）... 

Requirement already satisfied: pipenv in /opt/homebrew/lib/python3.11/site-packages (2023.6.12)
Requirement already satisfied: certifi in /opt/homebrew/lib/python3.11/site-packages (from pipenv) (2023.5.7)
Requirement already satisfied: setuptools>=67.0.0 in /opt/homebrew/lib/python3.11/site-packages (from pipenv) (67.6.1)
Requirement already satisfied: virtualenv-clone>=0.2.5 in /opt/homebrew/lib/python3.11/site-packages (from pipenv) (0.5.7)
Requirement already satisfied: virtualenv>=20.17.1 in /opt/homebrew/lib/python3.11/site-packages (from pipenv) (20.23.0)
Requirement already satisfied: distlib<1,>=0.3.6 in /opt/homebrew/lib/python3.11/site-packages (from virtualenv>=20.17.1->pipenv) (0.3.6)
Requirement already satisfied: filelock<4,>=3.11 in /opt/homebrew/lib/python3.11/site-packages (from virtualenv>=20.17.1->pipenv) (3.12.2)
Requirement already satisfied: platformdirs<4,>=3.2 in /opt/homebrew/lib/python3.11/site-packages (from virtualenv>=20.17.1->pipenv) (3.5.3)

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python3.11 -m pip install --upgrade pip
-e 
 安装所有依赖项 ... 

Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/project.py", line 548, in _parse_pipfile
    return tomlkit.parse(contents)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/tomlkit/api.py", line 83, in parse
    return Parser(string).parse()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/tomlkit/parser.py", line 158, in parse
    key, value = self._parse_table()
                 ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/tomlkit/parser.py", line 1002, in _parse_table
    table.raw_append(_key, item)
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/tomlkit/items.py", line 1613, in raw_append
    self._value.append(key, _item)
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/tomlkit/container.py", line 284, in append
    raise KeyAlreadyPresent(key)
pipenv.vendor.tomlkit.exceptions.KeyAlreadyPresent: Key "psycopg2" already exists.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/pipenv", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/cli/command.py", line 450, in run
    do_run(
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/routines/shell.py", line 66, in do_run
    ensure_project(
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/utils/project.py", line 32, in ensure_project
    ensure_virtualenv(
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/utils/virtualenv.py", line 148, in ensure_virtualenv
    python = ensure_python(project, python=python)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/utils/virtualenv.py", line 239, in ensure_python
    python = project.required_python_version
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/project.py", line 231, in required_python_version
    required = self.parsed_pipfile.get("requires", {}).get("python_full_version")
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/project.py", line 526, in parsed_pipfile
    parsed = self._parse_pipfile(contents)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/project.py", line 552, in _parse_pipfile
    return toml.loads(contents)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tomllib/_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tomllib/_parser.py", line 349, in key_value_rule
    raise suffixed_err(src, pos, "Cannot overwrite a value")
tomllib.TOMLDecodeError: Cannot overwrite a value (at line 14, column 15)
-e 
 显示项目目录 ... 

Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/project.py", line 548, in _parse_pipfile
    return tomlkit.parse(contents)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/tomlkit/api.py", line 83, in parse
    return Parser(string).parse()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/tomlkit/parser.py", line 158, in parse
    key, value = self._parse_table()
                 ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/tomlkit/parser.py", line 1002, in _parse_table
    table.raw_append(_key, item)
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/tomlkit/items.py", line 1613, in raw_append
    self._value.append(key, _item)
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/tomlkit/container.py", line 284, in append
    raise KeyAlreadyPresent(key)
pipenv.vendor.tomlkit.exceptions.KeyAlreadyPresent: Key "psycopg2" already exists.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/pipenv", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/cli/command.py", line 450, in run
    do_run(
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/routines/shell.py", line 66, in do_run
    ensure_project(
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/utils/project.py", line 32, in ensure_project
    ensure_virtualenv(
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/utils/virtualenv.py", line 148, in ensure_virtualenv
    python = ensure_python(project, python=python)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/utils/virtualenv.py", line 239, in ensure_python
    python = project.required_python_version
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/project.py", line 231, in required_python_version
    required = self.parsed_pipfile.get("requires", {}).get("python_full_version")
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/project.py", line 526, in parsed_pipfile
    parsed = self._parse_pipfile(contents)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/project.py", line 552, in _parse_pipfile
    return toml.loads(contents)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tomllib/_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tomllib/_parser.py", line 349, in key_value_rule
    raise suffixed_err(src, pos, "Cannot overwrite a value")
tomllib.TOMLDecodeError: Cannot overwrite a value (at line 14, column 15)
-e 
 显示虚拟环境目录 ... 

Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/project.py", line 548, in _parse_pipfile
    return tomlkit.parse(contents)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/tomlkit/api.py", line 83, in parse
    return Parser(string).parse()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/tomlkit/parser.py", line 158, in parse
    key, value = self._parse_table()
                 ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/tomlkit/parser.py", line 1002, in _parse_table
    table.raw_append(_key, item)
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/tomlkit/items.py", line 1613, in raw_append
    self._value.append(key, _item)
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/tomlkit/container.py", line 284, in append
    raise KeyAlreadyPresent(key)
pipenv.vendor.tomlkit.exceptions.KeyAlreadyPresent: Key "psycopg2" already exists.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/pipenv", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/cli/command.py", line 450, in run
    do_run(
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/routines/shell.py", line 66, in do_run
    ensure_project(
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/utils/project.py", line 32, in ensure_project
    ensure_virtualenv(
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/utils/virtualenv.py", line 148, in ensure_virtualenv
    python = ensure_python(project, python=python)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/utils/virtualenv.py", line 239, in ensure_python
    python = project.required_python_version
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/project.py", line 231, in required_python_version
    required = self.parsed_pipfile.get("requires", {}).get("python_full_version")
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/project.py", line 526, in parsed_pipfile
    parsed = self._parse_pipfile(contents)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/project.py", line 552, in _parse_pipfile
    return toml.loads(contents)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tomllib/_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tomllib/_parser.py", line 349, in key_value_rule
    raise suffixed_err(src, pos, "Cannot overwrite a value")
tomllib.TOMLDecodeError: Cannot overwrite a value (at line 14, column 15)
-e 
 项目后端部署完成！启动中... 

Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/project.py", line 548, in _parse_pipfile
    return tomlkit.parse(contents)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/tomlkit/api.py", line 83, in parse
    return Parser(string).parse()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/tomlkit/parser.py", line 158, in parse
    key, value = self._parse_table()
                 ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/tomlkit/parser.py", line 1002, in _parse_table
    table.raw_append(_key, item)
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/tomlkit/items.py", line 1613, in raw_append
    self._value.append(key, _item)
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/tomlkit/container.py", line 284, in append
    raise KeyAlreadyPresent(key)
pipenv.vendor.tomlkit.exceptions.KeyAlreadyPresent: Key "psycopg2" already exists.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/pipenv", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/cli/command.py", line 450, in run
    do_run(
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/routines/shell.py", line 66, in do_run
    ensure_project(
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/utils/project.py", line 32, in ensure_project
    ensure_virtualenv(
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/utils/virtualenv.py", line 148, in ensure_virtualenv
    python = ensure_python(project, python=python)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/utils/virtualenv.py", line 239, in ensure_python
    python = project.required_python_version
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/project.py", line 231, in required_python_version
    required = self.parsed_pipfile.get("requires", {}).get("python_full_version")
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/project.py", line 526, in parsed_pipfile
    parsed = self._parse_pipfile(contents)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pipenv/project.py", line 552, in _parse_pipfile
    return toml.loads(contents)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tomllib/_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tomllib/_parser.py", line 349, in key_value_rule
    raise suffixed_err(src, pos, "Cannot overwrite a value")
tomllib.TOMLDecodeError: Cannot overwrite a value (at line 14, column 15)

# zhangwenqian @ BMP in ~/UNSW/capstone-project-3900w18aZEAL/backend on git:dev_frontend x [23:12:46] C:1
$ 

